/**
 * LinhSinhVN — Reproduction System Constants
 *
 * Machine-readable reasons and domain enumerations for reproduction.
 */

export const ELIGIBILITY_REASONS = Object.freeze({
  ORGANISM_NOT_ALIVE: 'ORGANISM_NOT_ALIVE',
  SPECIES_INCOMPATIBLE: 'SPECIES_INCOMPATIBLE',
  SEX_INCOMPATIBLE: 'SEX_INCOMPATIBLE',
  STAGE_INCOMPATIBLE: 'STAGE_INCOMPATIBLE',
  AGE_INSUFFICIENT: 'AGE_INSUFFICIENT',
  COOLDOWN_ACTIVE: 'COOLDOWN_ACTIVE',
  INSUFFICIENT_ENERGY: 'INSUFFICIENT_ENERGY',
  REPRODUCTIVELY_BLOCKED: 'REPRODUCTIVELY_BLOCKED'
});

export const REPRODUCTION_EVENTS = Object.freeze({
  REPRODUCTION_COMPLETED: 'REPRODUCTION_COMPLETED',
  ORGANISM_BORN: 'ORGANISM_BORN'
});

export const EVENT_DOMAINS = Object.freeze({
  REPRODUCTION: 'REPRODUCTION',
  LIFECYCLE: 'LIFECYCLE'
});
